[package]
name = "io"
version = "0.1.0"
edition = "2024"

[dependencies]
umya-spreadsheet = "2.3.3"
csv = "1.4.0"
pgtemp = "0.6.0"
tokio = "1.48.0"
sqlx = { version = "0.8.6", features=["runtime-tokio", "postgres"] }
