name: Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3
    - uses: cargo-bins/cargo-binstall@main

    - name: Install postgres
      run: sudo apt install -y postgresql postgresql-client
    - name: Update path
      run: find /usr/lib/postgresql/ -type d -name "bin" >> $GITHUB_PATH
    
    - name: Install testing toolchains
      run: cargo binstall cargo-nextest cargo-llvm-cov --no-confirm --locked

    - name: Run tests
      run: just test
    
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./target/lcov.info
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}